import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "./global.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nft Market',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-[#3b4260] to-[#401e3c]">{children}</body>
    </html>
  )
}
